name: Deploy Build Artifacts

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Checkout Deploy Branch
        run: |
          git checkout deploy || git checkout -b deploy

      - name: Remove All Files Except Build Artifacts
        run: |
          find . -maxdepth 1 ! -name '.next' ! -name '.' ! -name '.git' -exec sh -c 'git ls-files -o --exclude-standard -z "$1" | xargs -0 git rm -r' sh {} \; || true

      - name: Commit and Push Build Artifacts
        run: |
          git add .next/
          git commit -m "Keep only build artifacts" || true  # 이미 최신 상태라면 커밋을 건너뜀
          git push origin deploy
