name: Build and Push to Deploy Branch

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Switch to deploy branch
        run: |
          git checkout -b temp-deploy
          git rm -r *
          git restore --source=HEAD .next
          git add .next/
          git commit -m "Keep only build artifacts"

      - name: Push to deploy branch
        run: git push origin temp-deploy